"""add historial eliminacion personajes y peliculas

Revision ID: 098a60ecb09e
Revises: cf6aafe913ec
Create Date: 2025-06-03 23:36:08.355407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '098a60ecb09e'
down_revision: Union[str, None] = 'cf6aafe913ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_eliminaciones_peliculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_eliminaciones_peliculas_id'), 'historial_eliminaciones_peliculas', ['id'], unique=False)
    op.create_table('historial_eliminaciones_personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_eliminaciones_personajes_id'), 'historial_eliminaciones_personajes', ['id'], unique=False)
    op.drop_index(op.f('ix_historial_eliminaciones_id'), table_name='historial_eliminaciones')
    op.drop_table('historial_eliminaciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_eliminaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('historial_eliminaciones_pkey'))
    )
    op.create_index(op.f('ix_historial_eliminaciones_id'), 'historial_eliminaciones', ['id'], unique=False)
    op.drop_index(op.f('ix_historial_eliminaciones_personajes_id'), table_name='historial_eliminaciones_personajes')
    op.drop_table('historial_eliminaciones_personajes')
    op.drop_index(op.f('ix_historial_eliminaciones_peliculas_id'), table_name='historial_eliminaciones_peliculas')
    op.drop_table('historial_eliminaciones_peliculas')
    # ### end Alembic commands ###
