"""agregar imagen_url a Personaje y Pelicula

Revision ID: 9fd656d7c029
Revises: e1e3964b2605
Create Date: 2025-06-02 17:23:17.295896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd656d7c029'
down_revision: Union[str, None] = 'e1e3964b2605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peliculas', sa.Column('img_url', sa.String(), nullable=True))
    op.add_column('personajes', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personajes', 'img_url')
    op.drop_column('peliculas', 'img_url')
    # ### end Alembic commands ###
