"""Corrige nombre columna pelicula_id

Revision ID: e1e3964b2605
Revises: 
Create Date: 2025-06-01 01:48:23.272888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e3964b2605'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personajes', sa.Column('pelicula_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'personajes', 'peliculas', ['pelicula_id'], ['id'])
    op.drop_column('personajes', 'pelicula')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personajes', sa.Column('pelicula', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'personajes', type_='foreignkey')
    op.drop_column('personajes', 'pelicula_id')
    # ### end Alembic commands ###
